config/routes.rb
Rails.application.routes.draw do
  root "todos#index"
  resources :todos

  resource :setting, only: [ :edit, :update ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/setting.rb
class Setting < ApplicationRecord
  validates :default_deadline_days, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 99 }
  validates :default_deadline_hours, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 23 }
  validates :default_deadline_minutes, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum :status, { wait: 0, doing: 1, done: 2 }
  validates :task, :deadline, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @setting = Setting.first || Setting.new
  end

  def update
    @setting = Setting.first || Setting.new
    if @setting.update(setting_params)
      redirect_to todos_path, notice: "設定を更新しました！"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def setting_params
    params.require(:setting).permit(:default_deadline_days, :default_deadline_hours, :default_deadline_minutes)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    if params[:status].present?
      @todos = Todo.where(status: Todo.statuses[params[:status]])
    else
      @todos = Todo.all
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new(params[:status])

    setting = Setting.first
    if setting
      @todo.deadline = (Time.current +
        setting.default_deadline_days.days +
        setting.default_deadline_hours.hour +
        setting.default_deadline_minutes.minutes)
        .strftime("%Y-%m-%dT%H:%M")
    end
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo, notice: "TODO を新規作成しました！"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "TODO を更新しました！" }
        format.json { head :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy!
    redirect_to todos_path(), notice: "TODO を削除しました！"
  end

  private

  def todo_params
    params.require(:todo).permit(:task, :priority, :deadline, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def priority_label(priority)
    case priority
    when 1 then "低"
    when 2 then "中"
    when 3 then "高"
    else "未設定"
    end
  end

  def status_label(status)
    case status
    when "wait" then "未着手"
    when "doing" then "着手中"
    when "done" then "完了"
    else "不明"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header-left">
        <span class="page-title"><%= yield(:page_title) %></span>
      </div>

      <div class="header-list">
        <ul>
          <li><%= link_to "TODO", todos_path %></li>
          <li><%= link_to "設定", edit_setting_path %></li>
        </ul>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/settings/edit.html.erb
<% content_for :page_title, "設定" %>

<% if @setting.errors.any? %>
  <div class="todo error_explanation spaced">
    <h2><%= pluralize(@setting.errors.count, "件のエラー") %>があります</h2>
    <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="todo">
  <h2>デフォルトの締切時間</h2>
  <%= form_with model: @setting, url: setting_path, local: true do |f| %>
    <p>
      現在時刻から
      <%= f.number_field :default_deadline_days, min: 0, max: 99 %> 日
      <%= f.number_field :default_deadline_hours, min: 0, max: 23 %> 時間
      <%= f.number_field :default_deadline_minutes, min: 0, max: 59 %> 分後
    </p>

  <%= f.submit "保存", class: "button button-align-left" %>
  <% end %>
</div>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <div class="todo error_explanation spaced">
    <h2><%= pluralize(@todo.errors.count, "件のエラー") %>があります</h2>
    <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="todo" data-status="<%= @todo.status %>">
  <%= form_with model: @todo, local: true do |form| %>
    <div>
      <%= form.label :task, "タスク" %>
      <%= form.text_field :task, class: "form-task" %>
    </div>
    <div>
      <%= form.label :priority, "優先度" %>
      <%= form.select :priority, options_for_select([["高", 3], ["中", 2], ["低", 1]], @todo.priority) %>
    </div>
    <% unless @todo.new_record? %>
      <div>
        <%= form.label :status, "状態" %>
        <%= form.select :status, options_for_select([["未着手", "wait"], ["着手中", "doing"], ["完了", "done"]], @todo.status) %>
      </div>
    <% end %>
    <div>
      <%= form.label :deadline, "締切日" %>
      <%= form.datetime_local_field :deadline %>
    </div>

    <div>
      <%= form.submit @todo.new_record? ? "作成" : "更新", class: "button button-align-left" %>
    </div>
    <% unless @todo.new_record? %>
      <%= link_to "削除", todo_path(@todo), class: "button button-red button-align-left", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
    <% end %>
  <% end %>
</div>

app/views/todos/edit.html.erb
<% content_for :page_title, "編集" %>

<%= render "form" %>

<%= link_to "一覧へ戻る", todos_path, class: "button spaced" %>

app/views/todos/index.html.erb
<% content_for :page_title, "TODO 一覧" %>

<%= link_to "新規作成", new_todo_path, class: "button" %>
<%= link_to "TODO 一覧", todos_path, class: "button" %>
<br>
<%= link_to "未着手の TODO 一覧", todos_path(status: "wait"), class: "button" %>
<%= link_to "着手中の TODO 一覧", todos_path(status: "doing"), class: "button button-yellow" %>
<%= link_to "完了済みの TODO 一覧", todos_path(status: "done"), class: "button button-gray" %>

<% if notice %>
  <div class="notice_explanation spaced">
    <%= notice %>
  </div>
<% end %>

<% @todos.each do |todo| %>
  <div class="spaced">
    <ul class="todo" data-status="<%= todo.status %>">
      <li><%= "タスク：#{todo.task}" %></li>
      <li><%= "優先度：#{priority_label(todo.priority)}" %></li>
      <li><%= "締切日：#{todo.deadline ? l(todo.deadline) : "なし"}" %></li>
      <li><%= link_to "詳細", todo_path(todo), class: "button button-align-left" %></li>
      <li><%= link_to "編集", edit_todo_path(todo), class: "button button-align-left" %></li>
      <li><%= link_to "削除", todo_path(todo), class: "button button-red button-align-left", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></li>
    </ul>
  </div>
<% end %>

app/views/todos/new.html.erb
<% content_for :page_title, "新規作成" %>

<%= render "form" %>

<%= link_to "一覧へ戻る", todos_path, class: "button spaced" %>

app/views/todos/show.html.erb
<% content_for :page_title, "詳細" %>

<% if notice %>
  <div class="notice_explanation spaced">
    <%= notice %>
  </div>
<% end %>

<div>
  <ul class="todo" data-status="<%= @todo.status %>">
    <li><%= "タスク：#{@todo.task}" %></li>
    <li><%= "優先度：#{priority_label(@todo.priority)}" %></li>
    <li><%= "状態：#{status_label(@todo.status)}" %></li>
    <li><%= "締切日：#{@todo.deadline ? l(@todo.deadline) : "なし"}" %></li>
    <li><%= "作成日：#{l(@todo.created_at)}" %></li>
    <li><%= "最終更新日：#{l(@todo.updated_at)}" %></li>
  </ul>
</div>

<%= link_to "一覧へ戻る", todos_path, class: "button spaced" %>